/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountsGetDetails } from "../../funcs/accountsGetDetails.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$accountsGetDetails: ToolDefinition = {
  name: "accounts-get-details",
  description: `Get account details

Get current account balance and other details of your account. You can check also account limit and if account is main one. Main accounts have unlimited privileges and using [User Panel](https://panel.szybkisms.pl) you can create as many subaccounts as you need.
 
This method doesn't get any parameters. As a successful result an \`AccountResponse\` object will be returned with properties describing details of current account you are logged in using an API Access Token.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await accountsGetDetails(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
