/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { commonPing } from "../../funcs/commonPing.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$commonPing: ToolDefinition = {
  name: "common_ping",
  description: `Checks API availability and version

Check the API connection and the current API availability status. Also you will get the current API version number. The method doesn't accept any parameters.

As a successful result a \`PingResponse\` object will be returned.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await commonPing(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
