/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { messagesMmsSend } from "../../funcs/messagesMmsSend.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.SendMmsRequestBody$inboundSchema,
};

export const tool$messagesMmsSend: ToolDefinition<typeof args> = {
  name: "messages-mms-send",
  description: `Send MMS Messages

Send single or multiple MMS messages at the same time. You can pass as a parameter \`MmsMessage\` object (for single message) or \`array\` of \`MmsMessage\` objects (for multiple messages). Each \`MmsMessage\` object has several properties, describing message parameters such recipient phone number, content of the message, attachments or scheduled sending date, etc. This method will accept maximum **50** messages in one call.

As a successful result a \`SendMmsResponse\` object will be returned with \`result\` property containing array of \`Message\` objects, one object per each single message. You should check the \`statusCode\` property of each \`Message\` object to make sure which were accepted by gateway (queued) and which were rejected. In case of rejection, \`statusDescription\` property will include a reason.

\`SendSmsResponse\` will also include \`headers\` array with \`X-Success-Count\` (a count of messages which were processed successfully), \`X-Error-Count\` (count of messages which were rejected) and \`X-Sandbox\` (if a request was made in Sandbox or Production system) elements.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await messagesMmsSend(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
