/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sendersList } from "../../funcs/sendersList.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$sendersList: ToolDefinition = {
  name: "senders-list",
  description: `List allowed senders names

Get a list of allowed senders defined in your account. The method doesn't take any parameters.

As a successful result an \`array\` of \`Sender\` objects will be returned, each object per single sender.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await sendersList(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
