/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sendersDelete } from "../../funcs/sendersDelete.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteSenderRequest$inboundSchema,
};

export const tool$sendersDelete: ToolDefinition<typeof args> = {
  name: "senders_delete",
  description: `Delete a sender name

Removes defined sender name from your account. This method accepts \`DeleteSenderRequest\` object with \`sender\` property containing a **sender name** you want to remove. Sender name will be deleted immediately.

As a successful response there would be no Exception thrown.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await sendersDelete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
