/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sendersSetDefault } from "../../funcs/sendersSetDefault.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.SetDefaultSenderRequest$inboundSchema,
};

export const tool$sendersSetDefault: ToolDefinition<typeof args> = {
  name: "senders_set-default",
  description: `Set default sender name

Set default sender name to one of the senders names already defined on your account. This method accepts a \`SetDefaultSenderRequest\` object with \`sender\` property containing a **sender name** to be set as default on your account.

As a successful response no Exception will be thrown.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await sendersSetDefault(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
