/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountsGet } from "../funcs/accountsGet.js";
import { accountsGetSubaccount } from "../funcs/accountsGetSubaccount.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Accounts extends ClientSDK {
  /**
   * Get account details
   *
   * @remarks
   * Get current account balance and other details of your account. You can check also account limit and if account is main one. Main accounts have unlimited privileges and using [User Panel](https://panel.gsmservice.pl) you can create as many subaccounts as you need.
   *
   * This method doesn't get any parameters. As a successful result an `AccountResponse` object will be returned with properties describing details of current account you are logged in using an API Access Token.
   */
  async get(
    options?: RequestOptions,
  ): Promise<components.AccountResponse> {
    return unwrapAsync(accountsGet(
      this,
      options,
    ));
  }

  /**
   * Get subaccount details
   *
   * @remarks
   * Check account balance and other details such subcredit balance of a subaccount. Subaccounts are additional users who can access your account services and the details. You can restrict access level and setup privileges to subaccounts using [user panel](https://panel.gsmservice.pl).
   *
   * This method accepts an object `GetSubaccountDetailsRequest` with `userLogin` property. You should pass there the full subaccount login to access its data.
   *
   * As a successful result a `AccountResponse` object will be returned with properties describing details of subaccount with provided login.
   */
  async getSubaccount(
    request: operations.GetSubaccountDetailsRequest,
    options?: RequestOptions,
  ): Promise<components.AccountResponse> {
    return unwrapAsync(accountsGetSubaccount(
      this,
      request,
      options,
    ));
  }
}
