/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { commonPing } from "../funcs/commonPing.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Common extends ClientSDK {
  /**
   * Checks API availability and version
   *
   * @remarks
   * Check the API connection and the current API availability status. Also you will get the current API version number. The method doesn't accept any parameters.
   *
   * As a successful result a `PingResponse` object will be returned.
   */
  async ping(
    options?: RequestOptions,
  ): Promise<components.PingResponse> {
    return unwrapAsync(commonPing(
      this,
      options,
    ));
  }
}
