/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { incomingGetByIds } from "../funcs/incomingGetByIds.js";
import { incomingList } from "../funcs/incomingList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Incoming extends ClientSDK {
  /**
   * List the received SMS messages
   *
   * @remarks
   * Get the details of all received messages from your account incoming messages box. This method supports pagination so you have to pass `ListIncomingMessagesRequest` object with property `page` (number of page with received messages which you want to access) and a `limit` (max of received messages per page). Messages are fetched from the latest one. This method will accept maximum **50** as `limit` parameter value.
   *
   * As a successful result a `ListIncomingMessagesResponse` object will be returned with an array of `IncomingMessage` as `result` property, each object per single received message. `ListIncomingMessagesResponse` object will contain also a `headers` array property where you can find `X-Total-Results` (a total count of all received messages which are available in incoming box on your account), `X-Total-Pages` (a total number of all pages with results), `X-Current-Page` (A current page number) and `X-Limit` (messages count per single page) elements.
   */
  async list(
    request: operations.ListIncomingMessagesRequest,
    options?: RequestOptions,
  ): Promise<operations.ListIncomingMessagesResponse> {
    return unwrapAsync(incomingList(
      this,
      request,
      options,
    ));
  }

  /**
   * Get the incoming messages by IDs
   *
   * @remarks
   * Get the details of one or more received messages using their `ids`. This method accepts a `GetIncomingMessagesRequest` object with `ids` property containing an `array` of the unique incoming message *IDs*, which were given while receiving a messages. The method will accept maximum 50 identifiers in one call.
   *
   * As a successful result a `GetIncomingMessagesResponse` object will be returned with a `result` property containing array of `IncomingMessage` objects, each object per single received message. `GetIncomingMessagesResponse` object will contain also a `headers` array property where you can find `X-Success-Count` (a count of incoming messages which were found and returned correctly) and `X-Error-Count` (count of incoming messages which were not found) elements.
   */
  async getByIds(
    request: operations.GetIncomingMessagesRequest,
    options?: RequestOptions,
  ): Promise<operations.GetIncomingMessagesResponse> {
    return unwrapAsync(incomingGetByIds(
      this,
      request,
      options,
    ));
  }
}
