/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { outgoingMmsGetPrice } from "../funcs/outgoingMmsGetPrice.js";
import { outgoingMmsSend } from "../funcs/outgoingMmsSend.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Mms extends ClientSDK {
  /**
   * Check the price of MMS Messages
   *
   * @remarks
   * Check the price of single or multiple MMS messages at the same time before sending them. You can pass a single `MmsMessage` object (for single message) or `array` of `MmsMessage` objects (for multiple messages). Each `MmsMessage` object has several properties, describing message parameters such as recipient phone number, content of the message, attachments, etc.
   * The method will accept maximum **50** messages in one call.
   *
   * As a successful result a `GetMmsPriceResponse` object will be returned with `result` property containing `array` of `Price` objects, one object per each single message. You should check the `error` property of each `Price` object to make sure which were priced successfully and which finished with an error. Successfully priced messages will have `null` value of `error` property.
   *
   * `GetSmsPriceResponse` object will include also `headers` array with `X-Success-Count` (a count of messages which were processed successfully) and `X-Error-Count` (count of messages which were rejected) elements.
   */
  async getPrice(
    request: operations.GetMmsPriceRequestBody,
    options?: RequestOptions,
  ): Promise<operations.GetMmsPriceResponse> {
    return unwrapAsync(outgoingMmsGetPrice(
      this,
      request,
      options,
    ));
  }

  /**
   * Send MMS Messages
   *
   * @remarks
   * Send single or multiple MMS messages at the same time. You can pass as a parameter `MmsMessage` object (for single message) or `array` of `MmsMessage` objects (for multiple messages). Each `MmsMessage` object has several properties, describing message parameters such recipient phone number, content of the message, attachments or scheduled sending date, etc. This method will accept maximum **50** messages in one call.
   *
   * As a successful result a `SendMmsResponse` object will be returned with `result` property containing array of `Message` objects, one object per each single message. You should check the `statusCode` property of each `Message` object to make sure which were accepted by gateway (queued) and which were rejected. In case of rejection, `statusDescription` property will include a reason.
   *
   * `SendSmsResponse` will also include `headers` array with `X-Success-Count` (a count of messages which were processed successfully), `X-Error-Count` (count of messages which were rejected) and `X-Sandbox` (if a request was made in Sandbox or Production system) elements.
   */
  async send(
    request: operations.SendMmsRequestBody,
    options?: RequestOptions,
  ): Promise<operations.SendMmsResponse> {
    return unwrapAsync(outgoingMmsSend(
      this,
      request,
      options,
    ));
  }
}
