/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Accounts } from "./accounts.js";
import { Common } from "./common.js";
import { Incoming } from "./incoming.js";
import { Outgoing } from "./outgoing.js";
import { Senders } from "./senders.js";

export class Client extends ClientSDK {
  private _accounts?: Accounts;
  get accounts(): Accounts {
    return (this._accounts ??= new Accounts(this._options));
  }

  private _outgoing?: Outgoing;
  get outgoing(): Outgoing {
    return (this._outgoing ??= new Outgoing(this._options));
  }

  private _incoming?: Incoming;
  get incoming(): Incoming {
    return (this._incoming ??= new Incoming(this._options));
  }

  private _common?: Common;
  get common(): Common {
    return (this._common ??= new Common(this._options));
  }

  private _senders?: Senders;
  get senders(): Senders {
    return (this._senders ??= new Senders(this._options));
  }
}
