/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { outgoingSmsGetPrice } from "../funcs/outgoingSmsGetPrice.js";
import { outgoingSmsSend } from "../funcs/outgoingSmsSend.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Sms extends ClientSDK {
  /**
   * Check the price of SMS Messages
   *
   * @remarks
   * Check the price of single or multiple SMS messages at the same time before sending them. You have to pass as request body the `SmsMessage` object (for single message) or `array` of `SmsMessage` objects (for multiple messages). Each object has several properties, describing message parameters such recipient phone number, content of the message, type, etc. Please mind that some of them are required.
   * The system will accept maximum **100** messages in one call. If you need to check the price of larger volume of messages, please split it to several separate requests.
   *
   * As a successful result an `array` of `Price` objects will be returned, one object per each single message. You should check the `error` property of each message in a response body to make sure which were priced successfully and which finished with an error. Successfully priced messages will have `null` value of `error` property. Response will also include meta-data headers: `X-Success-Count` (a count of messages which were processed successfully) and `X-Error-Count` (count of messages which were rejected).
   *
   * If you send duplicated messages in one call, API will process such message only once. This request have to be authenticated using **API Access Token**.
   *
   * In case of an error, the `ErrorResponse` object will be returned with proper HTTP header status code (our error response complies with [RFC 9457](https://www.rfc-editor.org/rfc/rfc7807)).
   */
  async getPrice(
    request: operations.GetSmsPriceRequestBody,
    options?: RequestOptions,
  ): Promise<operations.GetSmsPriceResponse> {
    return unwrapAsync(outgoingSmsGetPrice(
      this,
      request,
      options,
    ));
  }

  /**
   * Send SMS Messages
   *
   * @remarks
   * Send single or multiple SMS messages at the same time. You have to pass as request body the `SmsMessage` object (for single message) or `array` of `SmsMessage` objects (for multiple messages). Each object has several properties, describing message parameters such recipient phone number, content of the message, type or scheduled sending date, etc. Please mind that some of them are required.
   * The system will accept maximum 100 messages in one call. If you need to send larger volume of messages, please split it to several separate requests.
   *
   * As a successful result an `array` with `Message` objects will be returned, one object per each single message. You should check the `status_code` property of each message in a response body to make sure which were accepted by gateway (queued) and which were rejected. In case of rejection, `status_description` property will include a reason. Response will also include meta-data headers: `X-Success-Count` (a count of messages which were processed successfully), `X-Error-Count` (count of messages which were rejected) and `X-Sandbox` (if a request was made in Sandbox or Production system).
   *
   * If you send duplicated messages in one call, API will process such message only once. This request have to be authenticated using **API Access Token**.
   *
   * In case of an error, the `ErrorResponse` object will be returned with proper HTTP header status code (our error response complies with [RFC 9457](https://www.rfc-editor.org/rfc/rfc7807)).
   */
  async send(
    request: operations.SendSmsRequestBody,
    options?: RequestOptions,
  ): Promise<operations.SendSmsResponse> {
    return unwrapAsync(outgoingSmsSend(
      this,
      request,
      options,
    ));
  }
}
