/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @gsmservice-pl/messaging-sdk-typescript SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx outgoingMmsSend.example.ts
 */

import { Client } from "@gsmservice-pl/messaging-sdk-typescript";

const client = new Client({
  bearer: "<YOUR API ACCESS TOKEN>",
});

async function main() {
  const result = await client.outgoing.mms.send({
    recipients: "+48999999999",
    subject: "This is a subject of the message",
    message: "This is MMS message content.",
    attachments: "<file body in base64 format>",
    date: null,
  });

  console.log(result);
}

main().catch(console.error);
