/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type GetMessagesRequest = {
  /**
   * Message IDs assigned by the system (separated by comma). The system will accept a maximum of 50 identifiers in one call.
   */
  ids: Array<number>;
};

export type GetMessagesResponse = {
  headers: { [k: string]: Array<string> };
  result: Array<components.Message>;
};

/** @internal */
export const GetMessagesRequest$inboundSchema: z.ZodType<
  GetMessagesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  ids: z.array(z.number().int()),
});

/** @internal */
export type GetMessagesRequest$Outbound = {
  ids: Array<number>;
};

/** @internal */
export const GetMessagesRequest$outboundSchema: z.ZodType<
  GetMessagesRequest$Outbound,
  z.ZodTypeDef,
  GetMessagesRequest
> = z.object({
  ids: z.array(z.number().int()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetMessagesRequest$ {
  /** @deprecated use `GetMessagesRequest$inboundSchema` instead. */
  export const inboundSchema = GetMessagesRequest$inboundSchema;
  /** @deprecated use `GetMessagesRequest$outboundSchema` instead. */
  export const outboundSchema = GetMessagesRequest$outboundSchema;
  /** @deprecated use `GetMessagesRequest$Outbound` instead. */
  export type Outbound = GetMessagesRequest$Outbound;
}

/** @internal */
export const GetMessagesResponse$inboundSchema: z.ZodType<
  GetMessagesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: z.array(components.Message$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type GetMessagesResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: Array<components.Message$Outbound>;
};

/** @internal */
export const GetMessagesResponse$outboundSchema: z.ZodType<
  GetMessagesResponse$Outbound,
  z.ZodTypeDef,
  GetMessagesResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: z.array(components.Message$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetMessagesResponse$ {
  /** @deprecated use `GetMessagesResponse$inboundSchema` instead. */
  export const inboundSchema = GetMessagesResponse$inboundSchema;
  /** @deprecated use `GetMessagesResponse$outboundSchema` instead. */
  export const outboundSchema = GetMessagesResponse$outboundSchema;
  /** @deprecated use `GetMessagesResponse$Outbound` instead. */
  export type Outbound = GetMessagesResponse$Outbound;
}
