/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

/**
 * To check the price of a single message or messages with the same content to multiple recipients, pass a single `SmsMessage` object with the properties of this message. To check the price of multiple messages with different content at the same time, pass as method param an `array` of `SmsMessage` objects with the properties of each message.
 */
export type GetSmsPriceRequestBody =
  | components.SmsMessage
  | Array<components.SmsMessage>;

export type GetSmsPriceResponse = {
  headers: { [k: string]: Array<string> };
  result: Array<components.Price>;
};

/** @internal */
export const GetSmsPriceRequestBody$inboundSchema: z.ZodType<
  GetSmsPriceRequestBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  components.SmsMessage$inboundSchema,
  z.array(components.SmsMessage$inboundSchema),
]);

/** @internal */
export type GetSmsPriceRequestBody$Outbound =
  | components.SmsMessage$Outbound
  | Array<components.SmsMessage$Outbound>;

/** @internal */
export const GetSmsPriceRequestBody$outboundSchema: z.ZodType<
  GetSmsPriceRequestBody$Outbound,
  z.ZodTypeDef,
  GetSmsPriceRequestBody
> = z.union([
  components.SmsMessage$outboundSchema,
  z.array(components.SmsMessage$outboundSchema),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetSmsPriceRequestBody$ {
  /** @deprecated use `GetSmsPriceRequestBody$inboundSchema` instead. */
  export const inboundSchema = GetSmsPriceRequestBody$inboundSchema;
  /** @deprecated use `GetSmsPriceRequestBody$outboundSchema` instead. */
  export const outboundSchema = GetSmsPriceRequestBody$outboundSchema;
  /** @deprecated use `GetSmsPriceRequestBody$Outbound` instead. */
  export type Outbound = GetSmsPriceRequestBody$Outbound;
}

/** @internal */
export const GetSmsPriceResponse$inboundSchema: z.ZodType<
  GetSmsPriceResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: z.array(components.Price$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type GetSmsPriceResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: Array<components.Price$Outbound>;
};

/** @internal */
export const GetSmsPriceResponse$outboundSchema: z.ZodType<
  GetSmsPriceResponse$Outbound,
  z.ZodTypeDef,
  GetSmsPriceResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: z.array(components.Price$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetSmsPriceResponse$ {
  /** @deprecated use `GetSmsPriceResponse$inboundSchema` instead. */
  export const inboundSchema = GetSmsPriceResponse$inboundSchema;
  /** @deprecated use `GetSmsPriceResponse$outboundSchema` instead. */
  export const outboundSchema = GetSmsPriceResponse$outboundSchema;
  /** @deprecated use `GetSmsPriceResponse$Outbound` instead. */
  export type Outbound = GetSmsPriceResponse$Outbound;
}
