/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SetDefaultSenderRequest = {
  /**
   * Sender name to set as default
   */
  sender: string;
};

export type SetDefaultSenderResponse = {
  headers: { [k: string]: Array<string> };
};

/** @internal */
export const SetDefaultSenderRequest$inboundSchema: z.ZodType<
  SetDefaultSenderRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  sender: z.string(),
});

/** @internal */
export type SetDefaultSenderRequest$Outbound = {
  sender: string;
};

/** @internal */
export const SetDefaultSenderRequest$outboundSchema: z.ZodType<
  SetDefaultSenderRequest$Outbound,
  z.ZodTypeDef,
  SetDefaultSenderRequest
> = z.object({
  sender: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SetDefaultSenderRequest$ {
  /** @deprecated use `SetDefaultSenderRequest$inboundSchema` instead. */
  export const inboundSchema = SetDefaultSenderRequest$inboundSchema;
  /** @deprecated use `SetDefaultSenderRequest$outboundSchema` instead. */
  export const outboundSchema = SetDefaultSenderRequest$outboundSchema;
  /** @deprecated use `SetDefaultSenderRequest$Outbound` instead. */
  export type Outbound = SetDefaultSenderRequest$Outbound;
}

export function setDefaultSenderRequestToJSON(
  setDefaultSenderRequest: SetDefaultSenderRequest,
): string {
  return JSON.stringify(
    SetDefaultSenderRequest$outboundSchema.parse(setDefaultSenderRequest),
  );
}

export function setDefaultSenderRequestFromJSON(
  jsonString: string,
): SafeParseResult<SetDefaultSenderRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SetDefaultSenderRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SetDefaultSenderRequest' from JSON`,
  );
}

/** @internal */
export const SetDefaultSenderResponse$inboundSchema: z.ZodType<
  SetDefaultSenderResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
  });
});

/** @internal */
export type SetDefaultSenderResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
};

/** @internal */
export const SetDefaultSenderResponse$outboundSchema: z.ZodType<
  SetDefaultSenderResponse$Outbound,
  z.ZodTypeDef,
  SetDefaultSenderResponse
> = z.object({
  headers: z.record(z.array(z.string())),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SetDefaultSenderResponse$ {
  /** @deprecated use `SetDefaultSenderResponse$inboundSchema` instead. */
  export const inboundSchema = SetDefaultSenderResponse$inboundSchema;
  /** @deprecated use `SetDefaultSenderResponse$outboundSchema` instead. */
  export const outboundSchema = SetDefaultSenderResponse$outboundSchema;
  /** @deprecated use `SetDefaultSenderResponse$Outbound` instead. */
  export type Outbound = SetDefaultSenderResponse$Outbound;
}

export function setDefaultSenderResponseToJSON(
  setDefaultSenderResponse: SetDefaultSenderResponse,
): string {
  return JSON.stringify(
    SetDefaultSenderResponse$outboundSchema.parse(setDefaultSenderResponse),
  );
}

export function setDefaultSenderResponseFromJSON(
  jsonString: string,
): SafeParseResult<SetDefaultSenderResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SetDefaultSenderResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SetDefaultSenderResponse' from JSON`,
  );
}
