/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * An object defining the message recipient telephone number with the message's custom identifier assigned by the User
 */
export type PhoneNumberWithCid = {
  /**
   * A telephone number in international format (with a plus sign and the country code at the beginning, e.g. +48 for Poland)
   */
  nr: string;
  /**
   * Custom message ID assigned by the User
   */
  cid?: string | undefined;
};

/** @internal */
export const PhoneNumberWithCid$inboundSchema: z.ZodType<
  PhoneNumberWithCid,
  z.ZodTypeDef,
  unknown
> = z.object({
  nr: z.string(),
  cid: z.string().optional(),
});

/** @internal */
export type PhoneNumberWithCid$Outbound = {
  nr: string;
  cid?: string | undefined;
};

/** @internal */
export const PhoneNumberWithCid$outboundSchema: z.ZodType<
  PhoneNumberWithCid$Outbound,
  z.ZodTypeDef,
  PhoneNumberWithCid
> = z.object({
  nr: z.string(),
  cid: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PhoneNumberWithCid$ {
  /** @deprecated use `PhoneNumberWithCid$inboundSchema` instead. */
  export const inboundSchema = PhoneNumberWithCid$inboundSchema;
  /** @deprecated use `PhoneNumberWithCid$outboundSchema` instead. */
  export const outboundSchema = PhoneNumberWithCid$outboundSchema;
  /** @deprecated use `PhoneNumberWithCid$Outbound` instead. */
  export type Outbound = PhoneNumberWithCid$Outbound;
}
